[package]
name = "cargo-snippet"
version = "0.1.0"
authors = ["hatoo <hato2000@gmail.com>"]
license = "MIT"

[lib]
plugin = true
path = "src/lib.rs"

[[bin]]
name = "cargo-snippet"
path = "src/main.rs"
required-features = ["binaries"]

[dependencies]
syn = { version = "0.12", features = ["full", "parsing", "extra-traits", "printing"], optional = true }
quote = { version = "0.4", optional = true }
rustfmt-nightly = { git = "https://github.com/rust-lang-nursery/rustfmt.git", optional = true }
glob = { version = "0.2", optional = true }
clap = { version = "2.29", optional = true }
serde = { version = "1.0", optional = true}
serde_derive = { version = "1.0", optional = true}
serde_json = { version = "1.0", optional = true}

[features]
binaries = ["syn", "quote", "rustfmt-nightly", "glob", "clap", "serde", "serde_derive", "serde_json"]